### PR TITLE
Add npm support

### PR DESCRIPTION
**Pull request by medsabir**
Adding npm support.

In order to improve the project, I would like to contribute to your project by adding the NPM support, I've read about NPM (you can see the links below):
- http://blog.npmjs.org/post/112064849860/using-jquery-plugins-with-npm
- http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm
- https://nodejs.org/en/blog/npm/peer-dependencies/  

However I added the `package.json`, this document is all you need to know to generate an NPM-compatible Stupid-Table-Plugin, it makes it easy to update the code that you're sharing, I also updated the `README.md` and added the installation instructions.

Best regards.
SABIR M'HAMMED

### CODE REVIEW

**Comment by idleberg** [comment]
This is more important than ever:

> warning bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467

**Comment by wuethrich44** [comment]
@joequery Is it possible to merge this soon

**Comment by johannesnagl** [comment]
This was fixed couple of minutes ago in https://github.com/joequery/Stupid-Table-Plugin/issues/154#issuecomment-336132105. This PR is therefore outdated.

**Comment by joequery** [comment]
I totally forgot about this PR. This package.json file looks more sophisticated. @johannesnagl which do you recommend I use?

**Comment by johannesnagl** [comment]
@joequery I never published my own library, but I think it's good to use the following keys:

```
"devDependencies": {},
"peerDependencies": {
  "jquery": ">= 1.7.0"
},
```

and remove the `dependencies` key from the current package.json.

Everything else looks fine to me in the current version!

**Comment by joequery** [comment]
Alright, updates made. Thanks everyone for the reminders for npm support.

**Comment by johannesnagl** [comment]
> Alright, updates made. Thanks everyone for the reminders for npm support.

can confirm, that my yarn.lock file now does not have the npm requirement it had in 1.1.2! <3

everything fine now!

**Pull request closed without merging**
