### PR TITLE
First pass at bower.json

### PR DESCRIPTION
**Pull request by nfm**
Not sure what you'd like to name this in Bower. I didn't set a version either as you don't have any tagged releases. Once you've merged this in and edited it to your liking, you can register the package on Bower like so: http://bower.io/docs/creating-packages/#register.

Cheers :smile:

### CODE REVIEW

**Comment by ringe** [comment]
I would like this, @joequery

**Comment by kenmoini** [comment]
I can concur, a bower.json file would be great to include in projects easily.

**Comment by joequery** [comment]
Should the `main` directive be the minified or unminified file? Or is that not so important?

**Comment by kenmoini** [comment]
I would believe it could be either.  Could do the unminified and user can have gulp then minify it or concatenate into a main vendor.js for applications.

**Comment by joequery** [comment]
I need to learn git tagging :disappointed: Stupid table is probably in a 1.0.0 state, so I can start there.

**Comment by joequery** [comment]
Bower support is finally added! Thanks for the issues everyone :)

**Pull request closed without merging**
